apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secret-store
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-south-1   # Change if needed
      auth:
        jwt:
          serviceAccountRef:
            name: default
